### ISSUE TITLE
Leaking/performance issues when adding/removing from tree

### ISSUE THREAD

**Issue by ccnokes** [mifi/react-lottie-player#35]
If the player is added/removed from the tree, something internally is leaking and it can cause the animation to jank and then the page to crash.

See this sandbox: https://codesandbox.io/s/elated-tdd-pvhkf?file=/src/App.tsx

Click the toggle button once. Everything works and the animation shows. Click it twice and it might be a bit slower. 3-4+ times (at least on my computer) it slows to a crawl and the page becomes unresponsive.

**Comment by mifi** [comment]
Thanks for nice report! I also managed to reproduce the issue with your codesandbox.

Seems this is an issue with upstream lottie-web. I found these: #1159 #2151

The solution is to use something like `lodash.clonedeep` on the `animationData`. e.g. `animationData={cloneDeep(animationData)}`

I will update react-lottie-player with this cloning code, because this is such a sneaky bug and it shouldn't be on the developers' shoulders to have to experience this crash.

**Comment by mifi** [comment]
this will be fixed in the next version

**Comment by victorlaforga** [comment]
I upgraded to 1.3.2 but with no result...
Could you help me with this?

https://pensive-gates-96535d.netlify.app/

<img width="1079" alt="Schermafbeelding 2021-06-24 om 08 55 21" src="https://user-images.githubusercontent.com/37700441/123216585-00647d00-d4ca-11eb-86b7-19d61cfd4f10.png">

**Comment by mifi** [comment]
I believe your issue is #30, please continue discussion there

**Comment by ccnokes** [comment]
🎉🎉🎉
